### ISSUE TITLE
tkLRFViewerコンポーネントのスケールとThreshold値

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/OpenRTM-aist-Python#175]
**Is your feature request related to a problem? Please describe.**
* 実際の4mレンジのLRFセンサーを使って、このサンプルコンポーネントを使おうとすると、起動時のデフォルトではうまくセンサー出力が表示できず、スライダーをシビアに動かしてスケールファクターを0.01とか0.02に設定しないとだめ。
* Threshold値が距離データがThresholdより小さい時に測距地を1000にしているが、論理的におかしく思える。
**Describe the solution you'd like**
* 内部で使っている距離データを描画時に10倍から100倍にする。現在はスケールファクターが1.0の時は1mあたり1ドットなので、100ドット1mか10ドット1mかその中間値ぐらいにするのが良い。
* Threshold値のハンドルを距離がThreshold値より大きい時に1000とかにするか、逆に小さい時に0
にするように変更　または、Threshold関係のインタフェースを削除して変更できなくする。

**Describe alternatives you've considered**
現状、ドキュメント側でこのサンプルは実際の使用時には現状の内部設定値が現実的でないのでソース変更を推奨の旨記載。

**Additional context**
なお変更をした場合、テストスクリプトで使っているテスト用RTCを変更する必要があるかもしれないのと、現在のドキュメントの変更も必要になります。　この副作用も考慮すると変更しないのもありです。

**Comment by kkunita** [comment]
Threshold値はセンサーが検出できなかった長い距離では0を出力するため、現在の仕様でOKのはずとのことでThreshold値のロジックの変更はいらないが、全体的スケール変更にともない、何等かのスケール変更は必要になるはず
