### ISSUE TITLE
Listenerのセット関数でautocleanとしてboolを引数にとるのをやめる

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTM-aist-Python#94]
**Describe the bug**

バグではないかもしれないが、Python版のListenerのAdd関数において、リスナオブジェクトに加え、autoclean（自動的にオブジェクトを削除するかどうか？）を引数にとり、ListenerHolder削除時に丁寧に消しているが、これはC++においては必要だが、Pythonでは不要なので、autoclean引数は廃止すべき。

**Comment by Nobu19800** [comment]
#107 で解決済みのためIssueのCloseをお願いします。
